# Builder stage
FROM openjdk:17-jdk-slim AS builder
WORKDIR spring_book_intro
ARG JAVA_FILE=target/*.jar
COPY ${JAVA_FILE} spring_book_intro.jar
RUN java -Djarmode=layertools -jar spring_book_intro.jar extract
  
  # Final stage
FROM openjdk:17-jdk-slim
WORKDIR spring_book_intro
COPY --from=builder spring_book_intro/dependencies/ ./
COPY --from=builder spring_book_intro/spring-boot-loader/ ./
COPY --from=builder spring_book_intro/snapshot-dependencies/ ./
COPY --from=builder spring_book_intro/application/ ./
ENTRYPOINT ["java", "org.springframework.boot.loader.launch.JarLauncher"]
EXPOSE 8080